pipeline {
    agent any

.console-output {
    background-color: black;
    color: #eee;
    }
    options { timestamps() }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/vogellacompany/saneclipse.git'

                // Run Maven on a Unix agent.
                sh "mvn clean verify"

               
            }

            post {
               
                success {
                    archiveArtifacts 'com.vogella.saneclipse.feature/target/*.jar'
                }
            }
        }
    }
}

