pipeline {
    agent any

 options {
        ansiColor('xterm')
    }
    stages {
        stage('Build') {
            steps {
                echo '\033[34mHello\033[0m \033[33mcolorful\033[0m \033[35mworld!\033[0m'
            }
        }
    }
}
    options { timestamps() }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/vogellacompany/saneclipse.git'

                // Run Maven on a Unix agent.
                sh "mvn clean verify"

               
            }

            post {
               
                success {
                    archiveArtifacts 'com.vogella.saneclipse.feature/target/*.jar'
                }
            }
        }
    }
}

